import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{ArrowRight,Code2,Database,Download,ExternalLink,Github,Mail,MapPin,Menu,Sparkles,X,Zap}from'lucide-react';import'./style.css';import character from'./assets/character-storyboard.png';
const projects=[['DAM Operations','React + Cloudflare Workers','Operations platform designed for multi-branch workflows, stock records and staff tools.'],['Stock Intelligence','Google Sheets + Apps Script','Automated stock processing, branch reporting and consumption analysis.'],['Schedule Analyzer','Python + Excel','Weekly schedule analysis with shift classification, overtime and branch summaries.'],['Delivery Note Scanner','Vision + OCR','Experimental document scanner that converts delivery notes into structured operational data.']];
function App(){const[menu,setMenu]=useState(false);const[x,setX]=useState(0);const[greet,setGreet]=useState(false);useEffect(()=>{const m=e=>{let n=(e.clientX/innerWidth)*2-1;setX(Math.max(-1,Math.min(1,n)));if(Math.abs(n)<.13)setGreet(true)};addEventListener('mousemove',m);return()=>removeEventListener('mousemove',m)},[]);return <><nav><a className="brand" href="#home"><Code2/>YASHWANTH.L</a><div className={'links '+(menu?'open':'')}>{['Home','About','Skills','Experience','Projects','Contact'].map(i=><a onClick={()=>setMenu(false)} href={'#'+i.toLowerCase()}>{i}</a>)}</div><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav><main>
<section id="home" className="hero"><div className="heroCopy"><div className="pill"><span/> DATA PROGRAMMER & AUTOMATION DEVELOPER</div><h1>Hi, I'm<br/><em>Yashwanth.L</em></h1><p>I build automations, data systems and digital solutions that turn complex work into simple, scalable workflows.</p><div className="actions"><a className="primary" href="#projects">View my work <ArrowRight/></a><a className="secondary" href="#contact">Let's connect</a></div><div className="stats"><b>4+<small>Years experience</small></b><b>30+<small>Branches supported</small></b><b>100K+<small>Data operations</small></b></div></div>
<div className="character"><div className="orb"/><div className="hint">Move your cursor<br/><b>{greet?'Hey! 👋 Nice to meet you.':x<-.2?'Looking left 👀':x>.2?'Looking right 👀':'Come to the center 👋'}</b></div><div className={'avatar '+(greet?'hello':'')} style={{'--look':x}}><img src={character}/></div><div className="glassNote">Interactive character prototype<br/><span>cursor tracking + greeting state</span></div></div></section>
<section id="about" className="section split"><div><label>ABOUT ME</label><h2>More Than Just Code.</h2><p>I'm Yashwanth.L, a Data Programmer & Automation Developer working in Jeddah, Saudi Arabia. I focus on practical systems that make operations simpler, faster and more reliable.</p><p>My work sits between data, automation and web development — from Google Sheets workflows and reporting engines to full web applications.</p></div><div className="cards"><article><Zap/><h3>Problem Solver</h3><p>Turning operational problems into useful systems.</p></article><article><Sparkles/><h3>Always Learning</h3><p>Exploring better tools, architectures and workflows.</p></article><article><Database/><h3>Data Focused</h3><p>Making messy operational data understandable.</p></article><article><Code2/><h3>Builder</h3><p>Ideas become tools people can actually use.</p></article></div></section>
<section id="skills" className="section"><label>SKILLS</label><h2>Tools I Work With</h2><div className="skillrow">{['Python','JavaScript','React','Google Sheets','Apps Script','Cloudflare','Excel','SQL','Git & GitHub','Automation'].map(s=><span>{s}</span>)}</div></section>
<section id="experience" className="section"><label>EXPERIENCE</label><h2>Building Where Data Meets Operations.</h2><div className="timeline"><article><b>Current</b><h3>Data Programmer — DAM United</h3><p>Jeddah, Saudi Arabia</p><p>Automation, data operations, internal tools, reporting systems and workflow development across multi-brand operations.</p></article><article><b>Previous</b><h3>Help Desk & Business Development</h3><p>India</p><p>Built a foundation in technical support, problem solving, communication and business processes.</p></article></div></section>
<section id="projects" className="section"><label>SELECTED WORK</label><h2>Things I've Built.</h2><div className="projects">{projects.map(p=><article><div><small>{p[1]}</small><h3>{p[0]}</h3><p>{p[2]}</p></div><ExternalLink/></article>)}</div></section>
<section id="contact" className="contact"><div><label>LET'S BUILD SOMETHING</label><h2>Have an idea?<br/>Let's make it work.</h2><p>I'm interested in data, automation, internal tools and ambitious systems that solve real operational problems.</p></div><div className="contactCard"><MapPin/><span>Jeddah, Saudi Arabia</span><Mail/><span>Available for professional opportunities</span><Github/><span>GitHub-ready developer workflow</span></div></section>
</main><footer>© 2026 Yashwanth.L <span>Built with React • Ready for Cloudflare</span></footer></>};createRoot(document.getElementById('root')).render(<App/>);
